[project]
name = "eda-histopatologic-cancer-detect"
version = "0.1.0"
description = "Exploratory data analysis of histopatologic cancer data set"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.6.4",
]
